### ISSUE TITLE
Unable to Weave Different Modules

### ISSUE THREAD

**Issue by MatthewBerk** [freefair/android-gradle-plugins#53]
I am unable to get the plugins for AspectJ weaving on Android, such as this one
https://plugins.gradle.org/plugin/io.freefair.android.aspectj.post-compile-weaving
to weave files in different modules.

My project can be found here
https://github.com/MatthewBerk/2ModuleHeroProject
ritz module contains the AspectJ file Balloon.
app module contains the files I am trying to weave.

I was able to get this setup working in a simple Gradle java project using your plugin
https://plugins.gradle.org/plugin/io.freefair.aspectj.post-compile-weaving

It seems your new Android AspectJ weaving plugins are not weaving files found in different modules despite build.gradle setup looking correct. When I build the project, this message shows up
Task :ritz:transformClassesWithAspectjForRelease
com\example\ritz\Ballon.java [warning] no match for this type name: com.example.hero.Cheese [Xlint:invalidAbsoluteTypeName]

C:\Users\Matthew\Documents\newAttemptAtAndroid\Hero\ritz\build\intermediates\javac\release\classes!com\example\ritz\Ballon.class [warning] advice defined in com.example.ritz.Ballon has not been applied [Xlint:adviceDidNotMatch]

As you showed, the plugin does work when weaving files in same module/package as AspectJ file
https://github.com/larsgrefer/SimpleAndroidProject

Is there something special I need to do for Android build.gradle files or is it the plugin? Thank you again for designing this plugin.

**Comment by larsgrefer** [comment]
Have a look at https://github.com/MatthewBerk/2ModuleHeroProject/pull/1

The main "problem" is, that the `aspect` and `inpath` configurations can't handle android libraries (aar files) but only java libraries (jar files).

**Comment by MatthewBerk** [comment]
Thank you larsgrefer. New setup seems to work so far, just need to remember to use java libraries for aspectJ files.  Do you intend to create configuration that can handle android libraries in the future?
